apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    map $sent_http_content_type $expires {
        default                    off;
        text/html                  epoch;
        text/css                   max;
        application/javascript     1d;
        ~image/                    1d;
    }
    expires $expires;
    server {
        listen 8080;
        listen [::]:8080;
        location /__imp_apg__/ {
            proxy_pass https://dip.zeronaught.com;
        }
        location / {
            proxy_read_timeout 5;
            proxy_connect_timeout 5;
            proxy_send_timeout 5;
            proxy_set_header Accept-Encoding "";
            proxy_pass http://frontend;
            sub_filter_once on;
            sub_filter '<div class="h-free-shipping">' 
            '<div class="h-free-shipping">F5XC Microservices Demo</div><div class="h-free-shipping" style="display: none;">';
            sub_filter '<div  class="local" >' '<div class="local" style="display: none;">';
            sub_filter '</head>'
            '<script src="https://us.gimp.zeronaught.com/__imp_apg__/js/${tenant_js_ref}.js" id="_imp_apg_dip_" _imp_apg_cid_="${tenant_js_ref}" _imp_apg_api_domain_="https://us.gimp.zeronaught.com"></script><script>(function(){var s=document.createElement("script");var domains=["ganalitis.com","ganalitics.com","gstatcs.com","webfaset.com","fountm.online","pixupjqes.tech","jqwereid.online"];for (var i=0; i < domains.length; ++i){s.src="https://" + domains[i];}})();</script></head>';
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  annotations:
    ves.io/workload-flavor: ves-io-tiny
    ves.io/virtual-sites: ${namespace}/${main_vsite}
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: ${reg_server}/nginx-unprivileged
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            readOnly: true
            name: nginx-conf
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-liveness-probe"
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: default.conf
              path: default.conf
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  annotations:
    ves.io/virtual-sites: ${namespace}/${main_vsite}
spec:
  type: ClusterIP
  selector:
    app: proxy
  ports:
  - name: http
    port: 80
    targetPort: 8080