apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
        listen 8080;
        listen [::]:8080;
        location / {
            sub_filter_once on;
            sub_filter_types text/html;
            proxy_set_header Accept-Encoding "";
            proxy_pass http://frontend;
            sub_filter '</head>'
            '${injected_js}</head>';
        }
        location /__imp_apg__/ {
            proxy_pass https://dip.zeronaught.com;
        } 
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-injector
  annotations:
    ves.io/workload-flavor: ves-io-medium
    ves.io/virtual-sites: ${namespace}/${main_vsite}
spec:
  selector:
    matchLabels:
      app: proxy-injector
  template:
    metadata:
      labels:
        app: proxy-injector
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: ${reg_server}/nginx-unprivileged
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            readOnly: true
            name: nginx-conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: default.conf
              path: default.conf
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-injector
  annotations:
    ves.io/virtual-sites: ${namespace}/${main_vsite}
spec:
  type: ClusterIP
  selector:
    app: proxy-injector
  ports:
  - name: http
    port: 80
    targetPort: 8080