kind: Secret
apiVersion: v1
metadata:
  name: registry-secret
  namespace: ${namespace}
  annotations:
    ves.io/container-registry-secret: "true"
    ves.io/virtual-sites: ${namespace}/${spoke_vsite}, ${namespace}/${hub_vsite}
data:
  password: ${reg_password_b64}
  server: ${reg_server_b64}
  username: ${reg_username_b64}
type: ves.io/container-registry-secret