apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleaner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clean-pods
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clean-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: cleaner-sa
roleRef:
  kind: Role
  name: clean-pods
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pod-cleaner-cron
  annotations:
    ves.io/virtual-sites: demo-app/demo-app-state
spec:
  schedule: "*/6 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            ves.io/workload-flavor: tiny
            ves.io/virtual-sites: demo-app/demo-app-state
        spec:
          serviceAccountName: cleaner-sa
          volumes:
          - name: vault-token
            projected:
              sources:
              - serviceAccountToken:
                path: vault-token
                expirationSeconds: 3600
          containers:
            - name: cleaner
              image: registry.f5demos.com/pod-cleaner
              volumeMounts:
              - mountPath: /var/run/secrets/token
                name: vault-token
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          imagePullSecrets:
            - name: registry-secret
      backoffLimit: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-cleaner-vol
  annotations:
    ves.io/virtual-sites: demo-app/demo-app-state
spec:
  accessModes:
    - ReadWriteOnce          
  resources:
    requests:
      storage: 1Mi
  volumeMode: Filesystem