kind: Secret
apiVersion: v1
metadata:
  name: registry-secret
  namespace: ${utility_namespace}
  annotations:
    ves.io/container-registry-secret: "true"
    ves.io/virtual-sites: ${utility_namespace}/${utility_vsite}
data:
  password: ${reg_password_b64}
  server: ${reg_server_b64}
  username: ${reg_username_b64}
type: ves.io/container-registry-secret