apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: shop-traffic-gen-test
spec:
  schedule: "*/6 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: volt-traffic-gen
              image: registry.f5demos.com/volt-traffic-gen
              env:
                - name: DURATION
                  value: 5m
                - name: TARGET_URL
                  value: ${target_url}
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          imagePullSecrets:
            - name: f5demos-registry-secret
---
kind: Secret
apiVersion: v1
metadata:
  name: f5demos-registry-secret
  namespace: ${namespace}
  annotations:
    ves.io/container-registry-secret: "true"
    ves.io/virtual-sites: ${namespace}/${namespace}-vs
data:
  password: ${reg_password}
  server: ${reg_server}
  username: ${reg_username}
type: ves.io/container-registry-secret