name: container_build

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to private container registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.PRIVATE_REG }}
          username: ${{ secrets.PRIVATE_REG_USER }}
          password: ${{ secrets.PRIVATE_REG_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./loadgen-container
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.PRIVATE_REG }}/volt-traffic-gen:latest
